### ISSUE TITLE
Full-screen native ads template

### ISSUE THREAD

**Issue by tmxdyf** [googleads/googleads-mobile-android-native-templates#47]
Thanks for providing the native ad template. It would be great if you could provide a full-screen native ad template.

[Full-screen native ads](https://developers.google.com/admob/android/native/full-screen)

**Comment by NVentimiglia** [comment]
Hi @tmxdyf 

We have full screen native samples here : https://github.com/googleads/googleads-mobile-android-examples/tree/main/java/admob/FullScreenNativeExample

**Comment by ericleich** [comment]
We decided that it didn't make sense to provide a full screen template in this project because full screen ads on social apps such as Instagram will try to mimic the experience of content, which has other UI elements other than just the ad elements. This is not something easily replicated in a plug-and-play layout since you would most likely want to modify it.

If you think you want a full screen layout fully managed for you, interstitial ads would likely better meet your requirements.
